name: Cross-Layer Synchronization Check

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'blvm-spec/**'
      - 'blvm-consensus/**'
      - 'blvm-protocol/**'
      - 'blvm-node/**'
      - 'governance/config/cross-layer-rules.yml'
  push:
    branches: [main, develop]
    paths:
      - 'blvm-spec/**'
      - 'blvm-consensus/**'
      - 'governance/config/cross-layer-rules.yml'

jobs:
  cross-layer-validation:
    name: Validate Cross-Layer Synchronization
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain-file: rust-toolchain.toml
          components: rustfmt, clippy
      
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            blvm-commons/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build blvm-commons
        working-directory: blvm-commons
        run: |
          cargo build --release
          echo "✅ blvm-commons built successfully"
      
      - name: Load Cross-Layer Rules
        id: load_rules
        run: |
          if [ -f "governance/config/cross-layer-rules.yml" ]; then
            echo "✅ Cross-layer rules file found"
            echo "rules_file=governance/config/cross-layer-rules.yml" >> $GITHUB_OUTPUT
          else
            echo "❌ Cross-layer rules file not found"
            exit 1
          fi
      
      - name: Check File Correspondence
        id: check_correspondence
        working-directory: blvm-commons
        run: |
          echo "Checking file correspondence between Orange Paper and Consensus Proof..."
          
          # This is a placeholder for actual validation
          # In a full implementation, this would use the blvm-commons validation logic
          # to check if files in Orange Paper have corresponding files in Consensus Proof
          
          ORANGE_PAPER_RULES=$(find ../blvm-spec -path "*/consensus-rules/*" -type f 2>/dev/null | wc -l || echo "0")
          CONSENSUS_PROOF_PROOFS=$(find ../blvm-consensus -path "*/proofs/*" -type f 2>/dev/null | wc -l || echo "0")
          
          echo "blvm-spec (Orange Paper) consensus rules: $ORANGE_PAPER_RULES"
          echo "blvm-consensus proofs: $CONSENSUS_PROOF_PROOFS"
          
          if [ "$ORANGE_PAPER_RULES" -gt 0 ] && [ "$CONSENSUS_PROOF_PROOFS" -eq 0 ]; then
            echo "⚠️ blvm-spec has rules but blvm-consensus has no proofs"
            echo "correspondence_ok=false" >> $GITHUB_OUTPUT
          else
            echo "✅ File correspondence appears OK"
            echo "correspondence_ok=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Check Version Pinning
        id: check_version_pinning
        run: |
          echo "Checking version pinning references..."
          
          # Check if blvm-consensus references blvm-spec (Orange Paper) versions
          VERSION_REFS=$(grep -r "@blvm-spec-version\|blvm-spec@v\|@orange-paper-version\|orange-paper@v" blvm-consensus/ 2>/dev/null | wc -l || echo "0")
          
          echo "Version references found: $VERSION_REFS"
          
          if [ "$VERSION_REFS" -eq 0 ]; then
            echo "⚠️ No blvm-spec (Orange Paper) version references found in blvm-consensus"
            echo "version_pinning_ok=false" >> $GITHUB_OUTPUT
          else
            echo "✅ Version pinning references found"
            echo "version_pinning_ok=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Validate No Consensus Modifications
        id: check_consensus_mods
        run: |
          echo "Checking that Reference Node doesn't modify consensus rules..."
          
          # Check if blvm-node imports consensus-critical modules from blvm-consensus
          # rather than implementing its own
          CONSENSUS_IMPORTS=$(grep -r "blvm_consensus\|blvm-consensus" blvm-node/src/ 2>/dev/null | grep -i "use\|mod\|import" | wc -l || echo "0")
          
          echo "blvm-consensus imports in blvm-node: $CONSENSUS_IMPORTS"
          
          if [ "$CONSENSUS_IMPORTS" -gt 0 ]; then
            echo "✅ blvm-node uses blvm-consensus (correct)"
            echo "consensus_mods_ok=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ blvm-node may not be using blvm-consensus properly"
            echo "consensus_mods_ok=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Full Validation (if blvm-commons supports it)
        working-directory: blvm-commons
        run: |
          # This would run the actual cross-layer validation from blvm-commons
          # For now, this is a placeholder
          echo "Running cross-layer validation..."
          
          # In a full implementation:
          # cargo run --bin blvm-commons -- validate-cross-layer \
          #   --blvm-spec ../blvm-spec \
          #   --blvm-consensus ../blvm-consensus \
          #   --rules ../governance/config/cross-layer-rules.yml
          
          echo "✅ Cross-layer validation logic exists in blvm-commons"
      
      - name: Validation Summary
        if: always()
        run: |
          echo "## Cross-Layer Synchronization Validation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| File Correspondence | ${{ steps.check_correspondence.outputs.correspondence_ok == 'true' && '✅ OK' || '⚠️ Needs Review' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version Pinning | ${{ steps.check_version_pinning.outputs.version_pinning_ok == 'true' && '✅ OK' || '⚠️ Needs Review' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| No Consensus Mods | ${{ steps.check_consensus_mods.outputs.consensus_mods_ok == 'true' && '✅ OK' || '⚠️ Needs Review' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.check_correspondence.outputs.correspondence_ok }}" != "true" ] || \
             [ "${{ steps.check_version_pinning.outputs.version_pinning_ok }}" != "true" ] || \
             [ "${{ steps.check_consensus_mods.outputs.consensus_mods_ok }}" != "true" ]; then
            echo "⚠️ Some validation checks failed. Please review the output above." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "✅ All cross-layer synchronization checks passed" >> $GITHUB_STEP_SUMMARY
          fi
