name: Cross-Layer Synchronization Check

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'bllvm-spec/**'
      - 'bllvm-consensus/**'
      - 'bllvm-protocol/**'
      - 'bllvm-node/**'
      - 'governance/config/cross-layer-rules.yml'
  push:
    branches: [main, develop]
    paths:
      - 'bllvm-spec/**'
      - 'bllvm-consensus/**'
      - 'governance/config/cross-layer-rules.yml'

jobs:
  cross-layer-validation:
    name: Validate Cross-Layer Synchronization
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain-file: rust-toolchain.toml
          components: rustfmt, clippy
      
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            bllvm-commons/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build bllvm-commons
        working-directory: bllvm-commons
        run: |
          cargo build --release
          echo "✅ bllvm-commons built successfully"
      
      - name: Load Cross-Layer Rules
        id: load_rules
        run: |
          if [ -f "governance/config/cross-layer-rules.yml" ]; then
            echo "✅ Cross-layer rules file found"
            echo "rules_file=governance/config/cross-layer-rules.yml" >> $GITHUB_OUTPUT
          else
            echo "❌ Cross-layer rules file not found"
            exit 1
          fi
      
      - name: Check File Correspondence
        id: check_correspondence
        working-directory: bllvm-commons
        run: |
          echo "Checking file correspondence between Orange Paper and Consensus Proof..."
          
          # This is a placeholder for actual validation
          # In a full implementation, this would use the bllvm-commons validation logic
          # to check if files in Orange Paper have corresponding files in Consensus Proof
          
          ORANGE_PAPER_RULES=$(find ../bllvm-spec -path "*/consensus-rules/*" -type f 2>/dev/null | wc -l || echo "0")
          CONSENSUS_PROOF_PROOFS=$(find ../bllvm-consensus -path "*/proofs/*" -type f 2>/dev/null | wc -l || echo "0")
          
          echo "bllvm-spec (Orange Paper) consensus rules: $ORANGE_PAPER_RULES"
          echo "bllvm-consensus proofs: $CONSENSUS_PROOF_PROOFS"
          
          if [ "$ORANGE_PAPER_RULES" -gt 0 ] && [ "$CONSENSUS_PROOF_PROOFS" -eq 0 ]; then
            echo "⚠️ bllvm-spec has rules but bllvm-consensus has no proofs"
            echo "correspondence_ok=false" >> $GITHUB_OUTPUT
          else
            echo "✅ File correspondence appears OK"
            echo "correspondence_ok=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Check Version Pinning
        id: check_version_pinning
        run: |
          echo "Checking version pinning references..."
          
          # Check if bllvm-consensus references bllvm-spec (Orange Paper) versions
          VERSION_REFS=$(grep -r "@bllvm-spec-version\|bllvm-spec@v\|@orange-paper-version\|orange-paper@v" bllvm-consensus/ 2>/dev/null | wc -l || echo "0")
          
          echo "Version references found: $VERSION_REFS"
          
          if [ "$VERSION_REFS" -eq 0 ]; then
            echo "⚠️ No bllvm-spec (Orange Paper) version references found in bllvm-consensus"
            echo "version_pinning_ok=false" >> $GITHUB_OUTPUT
          else
            echo "✅ Version pinning references found"
            echo "version_pinning_ok=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Validate No Consensus Modifications
        id: check_consensus_mods
        run: |
          echo "Checking that Reference Node doesn't modify consensus rules..."
          
          # Check if bllvm-node imports consensus-critical modules from bllvm-consensus
          # rather than implementing its own
          CONSENSUS_IMPORTS=$(grep -r "bllvm_consensus\|bllvm-consensus" bllvm-node/src/ 2>/dev/null | grep -i "use\|mod\|import" | wc -l || echo "0")
          
          echo "bllvm-consensus imports in bllvm-node: $CONSENSUS_IMPORTS"
          
          if [ "$CONSENSUS_IMPORTS" -gt 0 ]; then
            echo "✅ bllvm-node uses bllvm-consensus (correct)"
            echo "consensus_mods_ok=true" >> $GITHUB_OUTPUT
          else
            echo "⚠️ bllvm-node may not be using bllvm-consensus properly"
            echo "consensus_mods_ok=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Full Validation (if bllvm-commons supports it)
        working-directory: bllvm-commons
        run: |
          # This would run the actual cross-layer validation from bllvm-commons
          # For now, this is a placeholder
          echo "Running cross-layer validation..."
          
          # In a full implementation:
          # cargo run --bin bllvm-commons -- validate-cross-layer \
          #   --bllvm-spec ../bllvm-spec \
          #   --bllvm-consensus ../bllvm-consensus \
          #   --rules ../governance/config/cross-layer-rules.yml
          
          echo "✅ Cross-layer validation logic exists in bllvm-commons"
      
      - name: Validation Summary
        if: always()
        run: |
          echo "## Cross-Layer Synchronization Validation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| File Correspondence | ${{ steps.check_correspondence.outputs.correspondence_ok == 'true' && '✅ OK' || '⚠️ Needs Review' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Version Pinning | ${{ steps.check_version_pinning.outputs.version_pinning_ok == 'true' && '✅ OK' || '⚠️ Needs Review' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| No Consensus Mods | ${{ steps.check_consensus_mods.outputs.consensus_mods_ok == 'true' && '✅ OK' || '⚠️ Needs Review' }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.check_correspondence.outputs.correspondence_ok }}" != "true" ] || \
             [ "${{ steps.check_version_pinning.outputs.version_pinning_ok }}" != "true" ] || \
             [ "${{ steps.check_consensus_mods.outputs.consensus_mods_ok }}" != "true" ]; then
            echo "⚠️ Some validation checks failed. Please review the output above." >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "✅ All cross-layer synchronization checks passed" >> $GITHUB_STEP_SUMMARY
          fi
