name: Security Control Gate

on:
  pull_request:
    branches: [main, develop]
  push:
    tags: ['v*']

jobs:
  security-gate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for diff analysis
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          components: rustfmt, clippy
          
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Build governance-app
        run: |
          cd governance-app
          cargo build --release
          
      - name: Check Security Control Impact
        run: |
          cd governance-app
          cargo run --bin security-gate -- check-pr ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Detect Placeholders in Security-Critical Files
        run: |
          cd governance-app
          cargo run --bin security-gate -- check-placeholders
          
      - name: Verify Production Readiness for Releases
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd governance-app
          cargo run --bin security-gate -- verify-production-readiness
          # This will fail if any P0 controls are not certified
          
      - name: Update Security Control Status
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd governance-app
          cargo run --bin security-gate -- update-status
          # Updates security-control-status.yml
          
      - name: Comment Security Impact on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read security impact from file (generated by security-gate)
            const impactFile = path.join('governance-app', 'security-impact.json');
            
            if (fs.existsSync(impactFile)) {
              const impact = JSON.parse(fs.readFileSync(impactFile, 'utf8'));
              
              // Generate comment
              let comment = '## Security Control Impact\n\n';
              
              if (impact.affected_controls.length === 0) {
                comment += 'âœ… **No security controls affected** - Standard review process applies.';
              } else {
                // Impact level
                switch (impact.impact_level) {
                  case 'Critical':
                    comment += 'ðŸš¨ **CRITICAL IMPACT** - Multiple P0 security controls affected\n\n';
                    break;
                  case 'High':
                    comment += 'ðŸ”´ **HIGH IMPACT** - P0 security controls affected\n\n';
                    break;
                  case 'Medium':
                    comment += 'ðŸŸ¡ **MEDIUM IMPACT** - P1 security controls affected\n\n';
                    break;
                  case 'Low':
                    comment += 'ðŸŸ¢ **LOW IMPACT** - P2 security controls affected\n\n';
                    break;
                }
                
                // Affected controls
                comment += '### Affected Security Controls\n\n';
                impact.affected_controls.forEach(control => {
                  const priority_emoji = control.priority === 'P0' ? 'ðŸ”´' : 
                                        control.priority === 'P1' ? 'ðŸŸ¡' : 'ðŸŸ¢';
                  comment += `- ${priority_emoji} **${control.name}** (${control.id}) - ${control.description}\n`;
                });
                
                // Required tier
                if (impact.required_tier) {
                  comment += `\n### Required Governance Tier: **${impact.required_tier}**\n\n`;
                }
                
                // Additional requirements
                if (impact.additional_requirements.length > 0) {
                  comment += '### Additional Requirements\n\n';
                  impact.additional_requirements.forEach(req => {
                    comment += `- ${req}\n`;
                  });
                }
                
                // Production/audit blocking
                if (impact.blocks_production) {
                  comment += '\nâš ï¸ **This PR blocks production deployment** until P0 controls are certified.\n';
                }
                
                if (impact.blocks_audit) {
                  comment += '\nâš ï¸ **This PR blocks security audit** until P0 controls are implemented.\n';
                }
              }
              
              // Post comment
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }

  security-status-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.workflow_dispatch
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
          
      - name: Check Security Control Status
        run: |
          cd governance-app
          cargo run --bin security-gate -- status
          
      - name: Generate Security Report
        run: |
          cd governance-app
          cargo run --bin security-gate -- generate-report > security-report.md
          
      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: governance-app/security-report.md
          
      - name: Comment Security Status (if on main branch)
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const reportFile = path.join('governance-app', 'security-report.md');
            
            if (fs.existsSync(reportFile)) {
              const report = fs.readFileSync(reportFile, 'utf8');
              
              // Create issue with security status
              github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Security Control Status Report - ${new Date().toISOString().split('T')[0]}`,
                body: report,
                labels: ['security', 'status-report']
              });
            }













