name: Verify Consensus (Formal Verification)

on: 
  push:
    branches: [ main, develop ]
    paths:
      - 'blvm-consensus/**'
      - '.github/workflows/verify.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'blvm-consensus/**'
      - '.github/workflows/verify.yml'

jobs:
  verify:
    name: Formal Verification
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain-file: rust-toolchain.toml
          components: rustfmt, clippy
          
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            blvm-consensus/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # === REQUIRED: MUST PASS ===
      
      - name: Unit & Property Tests
        working-directory: blvm-consensus
        run: |
          cargo test --all-features --verbose
          echo "✅ All unit and property tests passed"
          
      - name: blvm-spec-lock Verification
        working-directory: blvm-consensus
        run: |
          # Run blvm-spec-lock verification
          cargo spec-lock verify --verbose
          echo "✅ All blvm-spec-lock proofs verified"
          
      - name: Clippy Linting
        working-directory: blvm-consensus
        run: |
          cargo clippy --all-features -- -D warnings
          echo "✅ Clippy linting passed"
          
      - name: Rustfmt Formatting
        working-directory: blvm-consensus
        run: |
          cargo fmt --all -- --check
          echo "✅ Code formatting verified"

      # === AUDIT TRAIL ===
      
      - name: Collect Verification Artifacts
        working-directory: blvm-consensus
        run: |
          mkdir -p artifacts
          tar -czf artifacts/verification-artifacts.tar.gz \
            target/ \
            Cargo.lock \
            Cargo.toml \
            src/ \
            tests/ \
            docs/ || true
          echo "📦 Verification artifacts collected"
          
      - name: OpenTimestamps Proof Log
        run: |
          # Install OpenTimestamps client
          sudo apt-get update
          sudo apt-get install -y opentimestamps-client
          
          # Create timestamp of verification artifacts
          if [ -f blvm-consensus/artifacts/verification-artifacts.tar.gz ]; then
            ots stamp blvm-consensus/artifacts/verification-artifacts.tar.gz
            echo "🔒 Verification artifacts timestamped with OpenTimestamps"
          else
            echo "⚠️ No verification artifacts found for timestamping"
          fi
          
      - name: Upload Verification Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: verification-proof-${{ github.run_id }}
          path: |
            blvm-consensus/artifacts/
          retention-days: 90
          
      - name: Verification Summary
        run: |
          echo "🎯 CONSENSUS VERIFICATION COMPLETE"
          echo "=================================="
          echo "✅ Unit tests: PASSED"
          echo "✅ Property tests: PASSED" 
            echo "✅ blvm-spec-lock proofs: VERIFIED"
          echo "✅ Clippy linting: PASSED"
          echo "✅ Code formatting: VERIFIED"
          echo "🔒 Audit trail: TIMESTAMPED"
          echo ""
          echo "This PR meets all formal verification requirements."
          echo "Consensus code is mathematically locked and auditable."














